/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VerifyCertificateIdRouteImport } from './routes/verify.$certificateId'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard.students'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardQuizzesRouteImport } from './routes/dashboard.quizzes'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardInstructorsRouteImport } from './routes/dashboard.instructors'
import { Route as DashboardEnrollmentsRouteImport } from './routes/dashboard.enrollments'
import { Route as DashboardDiscussionsRouteImport } from './routes/dashboard.discussions'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'
import { Route as DashboardContinueRouteImport } from './routes/dashboard.continue'
import { Route as DashboardCertificatesRouteImport } from './routes/dashboard.certificates'
import { Route as DashboardCategoriesRouteImport } from './routes/dashboard.categories'
import { Route as DashboardCatalogRouteImport } from './routes/dashboard.catalog'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard.assignments'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard.announcements'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardQuizzesQuizIdRouteImport } from './routes/dashboard.quizzes.$quizId'
import { Route as DashboardDiscussionsDiscussionIdRouteImport } from './routes/dashboard.discussions.$discussionId'
import { Route as DashboardCoursesNewRouteImport } from './routes/dashboard.courses.new'
import { Route as DashboardCoursesCourseIdRouteImport } from './routes/dashboard.courses.$courseId'
import { Route as DashboardCertificatesCertificateIdRouteImport } from './routes/dashboard.certificates.$certificateId'
import { Route as DashboardAssignmentsAssignmentIdRouteImport } from './routes/dashboard.assignments.$assignmentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VerifyCertificateIdRoute = VerifyCertificateIdRouteImport.update({
  id: '/verify/$certificateId',
  path: '/verify/$certificateId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuizzesRoute = DashboardQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInstructorsRoute = DashboardInstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnrollmentsRoute = DashboardEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDiscussionsRoute = DashboardDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContinueRoute = DashboardContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCertificatesRoute = DashboardCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCategoriesRoute = DashboardCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCatalogRoute = DashboardCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuizzesQuizIdRoute = DashboardQuizzesQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => DashboardQuizzesRoute,
} as any)
const DashboardDiscussionsDiscussionIdRoute =
  DashboardDiscussionsDiscussionIdRouteImport.update({
    id: '/$discussionId',
    path: '/$discussionId',
    getParentRoute: () => DashboardDiscussionsRoute,
  } as any)
const DashboardCoursesNewRoute = DashboardCoursesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardCoursesRoute,
} as any)
const DashboardCoursesCourseIdRoute =
  DashboardCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => DashboardCoursesRoute,
  } as any)
const DashboardCertificatesCertificateIdRoute =
  DashboardCertificatesCertificateIdRouteImport.update({
    id: '/$certificateId',
    path: '/$certificateId',
    getParentRoute: () => DashboardCertificatesRoute,
  } as any)
const DashboardAssignmentsAssignmentIdRoute =
  DashboardAssignmentsAssignmentIdRouteImport.update({
    id: '/$assignmentId',
    path: '/$assignmentId',
    getParentRoute: () => DashboardAssignmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRouteWithChildren
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/certificates': typeof DashboardCertificatesRouteWithChildren
  '/dashboard/continue': typeof DashboardContinueRoute
  '/dashboard/courses': typeof DashboardCoursesRouteWithChildren
  '/dashboard/discussions': typeof DashboardDiscussionsRouteWithChildren
  '/dashboard/enrollments': typeof DashboardEnrollmentsRoute
  '/dashboard/instructors': typeof DashboardInstructorsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/quizzes': typeof DashboardQuizzesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/assignments/$assignmentId': typeof DashboardAssignmentsAssignmentIdRoute
  '/dashboard/certificates/$certificateId': typeof DashboardCertificatesCertificateIdRoute
  '/dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRoute
  '/dashboard/courses/new': typeof DashboardCoursesNewRoute
  '/dashboard/discussions/$discussionId': typeof DashboardDiscussionsDiscussionIdRoute
  '/dashboard/quizzes/$quizId': typeof DashboardQuizzesQuizIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRouteWithChildren
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/certificates': typeof DashboardCertificatesRouteWithChildren
  '/dashboard/continue': typeof DashboardContinueRoute
  '/dashboard/courses': typeof DashboardCoursesRouteWithChildren
  '/dashboard/discussions': typeof DashboardDiscussionsRouteWithChildren
  '/dashboard/enrollments': typeof DashboardEnrollmentsRoute
  '/dashboard/instructors': typeof DashboardInstructorsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/quizzes': typeof DashboardQuizzesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/assignments/$assignmentId': typeof DashboardAssignmentsAssignmentIdRoute
  '/dashboard/certificates/$certificateId': typeof DashboardCertificatesCertificateIdRoute
  '/dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRoute
  '/dashboard/courses/new': typeof DashboardCoursesNewRoute
  '/dashboard/discussions/$discussionId': typeof DashboardDiscussionsDiscussionIdRoute
  '/dashboard/quizzes/$quizId': typeof DashboardQuizzesQuizIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRouteWithChildren
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/categories': typeof DashboardCategoriesRoute
  '/dashboard/certificates': typeof DashboardCertificatesRouteWithChildren
  '/dashboard/continue': typeof DashboardContinueRoute
  '/dashboard/courses': typeof DashboardCoursesRouteWithChildren
  '/dashboard/discussions': typeof DashboardDiscussionsRouteWithChildren
  '/dashboard/enrollments': typeof DashboardEnrollmentsRoute
  '/dashboard/instructors': typeof DashboardInstructorsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/quizzes': typeof DashboardQuizzesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/assignments/$assignmentId': typeof DashboardAssignmentsAssignmentIdRoute
  '/dashboard/certificates/$certificateId': typeof DashboardCertificatesCertificateIdRoute
  '/dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRoute
  '/dashboard/courses/new': typeof DashboardCoursesNewRoute
  '/dashboard/discussions/$discussionId': typeof DashboardDiscussionsDiscussionIdRoute
  '/dashboard/quizzes/$quizId': typeof DashboardQuizzesQuizIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/dashboard/announcements'
    | '/dashboard/assignments'
    | '/dashboard/catalog'
    | '/dashboard/categories'
    | '/dashboard/certificates'
    | '/dashboard/continue'
    | '/dashboard/courses'
    | '/dashboard/discussions'
    | '/dashboard/enrollments'
    | '/dashboard/instructors'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/quizzes'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/verify/$certificateId'
    | '/dashboard/'
    | '/dashboard/assignments/$assignmentId'
    | '/dashboard/certificates/$certificateId'
    | '/dashboard/courses/$courseId'
    | '/dashboard/courses/new'
    | '/dashboard/discussions/$discussionId'
    | '/dashboard/quizzes/$quizId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/dashboard/announcements'
    | '/dashboard/assignments'
    | '/dashboard/catalog'
    | '/dashboard/categories'
    | '/dashboard/certificates'
    | '/dashboard/continue'
    | '/dashboard/courses'
    | '/dashboard/discussions'
    | '/dashboard/enrollments'
    | '/dashboard/instructors'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/quizzes'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/verify/$certificateId'
    | '/dashboard'
    | '/dashboard/assignments/$assignmentId'
    | '/dashboard/certificates/$certificateId'
    | '/dashboard/courses/$courseId'
    | '/dashboard/courses/new'
    | '/dashboard/discussions/$discussionId'
    | '/dashboard/quizzes/$quizId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/dashboard/announcements'
    | '/dashboard/assignments'
    | '/dashboard/catalog'
    | '/dashboard/categories'
    | '/dashboard/certificates'
    | '/dashboard/continue'
    | '/dashboard/courses'
    | '/dashboard/discussions'
    | '/dashboard/enrollments'
    | '/dashboard/instructors'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/quizzes'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/verify/$certificateId'
    | '/dashboard/'
    | '/dashboard/assignments/$assignmentId'
    | '/dashboard/certificates/$certificateId'
    | '/dashboard/courses/$courseId'
    | '/dashboard/courses/new'
    | '/dashboard/discussions/$discussionId'
    | '/dashboard/quizzes/$quizId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VerifyCertificateIdRoute: typeof VerifyCertificateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/verify/$certificateId': {
      id: '/verify/$certificateId'
      path: '/verify/$certificateId'
      fullPath: '/verify/$certificateId'
      preLoaderRoute: typeof VerifyCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quizzes': {
      id: '/dashboard/quizzes'
      path: '/quizzes'
      fullPath: '/dashboard/quizzes'
      preLoaderRoute: typeof DashboardQuizzesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/instructors': {
      id: '/dashboard/instructors'
      path: '/instructors'
      fullPath: '/dashboard/instructors'
      preLoaderRoute: typeof DashboardInstructorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enrollments': {
      id: '/dashboard/enrollments'
      path: '/enrollments'
      fullPath: '/dashboard/enrollments'
      preLoaderRoute: typeof DashboardEnrollmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/discussions': {
      id: '/dashboard/discussions'
      path: '/discussions'
      fullPath: '/dashboard/discussions'
      preLoaderRoute: typeof DashboardDiscussionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/continue': {
      id: '/dashboard/continue'
      path: '/continue'
      fullPath: '/dashboard/continue'
      preLoaderRoute: typeof DashboardContinueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/certificates': {
      id: '/dashboard/certificates'
      path: '/certificates'
      fullPath: '/dashboard/certificates'
      preLoaderRoute: typeof DashboardCertificatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/categories': {
      id: '/dashboard/categories'
      path: '/categories'
      fullPath: '/dashboard/categories'
      preLoaderRoute: typeof DashboardCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/catalog': {
      id: '/dashboard/catalog'
      path: '/catalog'
      fullPath: '/dashboard/catalog'
      preLoaderRoute: typeof DashboardCatalogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quizzes/$quizId': {
      id: '/dashboard/quizzes/$quizId'
      path: '/$quizId'
      fullPath: '/dashboard/quizzes/$quizId'
      preLoaderRoute: typeof DashboardQuizzesQuizIdRouteImport
      parentRoute: typeof DashboardQuizzesRoute
    }
    '/dashboard/discussions/$discussionId': {
      id: '/dashboard/discussions/$discussionId'
      path: '/$discussionId'
      fullPath: '/dashboard/discussions/$discussionId'
      preLoaderRoute: typeof DashboardDiscussionsDiscussionIdRouteImport
      parentRoute: typeof DashboardDiscussionsRoute
    }
    '/dashboard/courses/new': {
      id: '/dashboard/courses/new'
      path: '/new'
      fullPath: '/dashboard/courses/new'
      preLoaderRoute: typeof DashboardCoursesNewRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/courses/$courseId': {
      id: '/dashboard/courses/$courseId'
      path: '/$courseId'
      fullPath: '/dashboard/courses/$courseId'
      preLoaderRoute: typeof DashboardCoursesCourseIdRouteImport
      parentRoute: typeof DashboardCoursesRoute
    }
    '/dashboard/certificates/$certificateId': {
      id: '/dashboard/certificates/$certificateId'
      path: '/$certificateId'
      fullPath: '/dashboard/certificates/$certificateId'
      preLoaderRoute: typeof DashboardCertificatesCertificateIdRouteImport
      parentRoute: typeof DashboardCertificatesRoute
    }
    '/dashboard/assignments/$assignmentId': {
      id: '/dashboard/assignments/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/dashboard/assignments/$assignmentId'
      preLoaderRoute: typeof DashboardAssignmentsAssignmentIdRouteImport
      parentRoute: typeof DashboardAssignmentsRoute
    }
  }
}

interface DashboardAssignmentsRouteChildren {
  DashboardAssignmentsAssignmentIdRoute: typeof DashboardAssignmentsAssignmentIdRoute
}

const DashboardAssignmentsRouteChildren: DashboardAssignmentsRouteChildren = {
  DashboardAssignmentsAssignmentIdRoute: DashboardAssignmentsAssignmentIdRoute,
}

const DashboardAssignmentsRouteWithChildren =
  DashboardAssignmentsRoute._addFileChildren(DashboardAssignmentsRouteChildren)

interface DashboardCertificatesRouteChildren {
  DashboardCertificatesCertificateIdRoute: typeof DashboardCertificatesCertificateIdRoute
}

const DashboardCertificatesRouteChildren: DashboardCertificatesRouteChildren = {
  DashboardCertificatesCertificateIdRoute:
    DashboardCertificatesCertificateIdRoute,
}

const DashboardCertificatesRouteWithChildren =
  DashboardCertificatesRoute._addFileChildren(
    DashboardCertificatesRouteChildren,
  )

interface DashboardCoursesRouteChildren {
  DashboardCoursesCourseIdRoute: typeof DashboardCoursesCourseIdRoute
  DashboardCoursesNewRoute: typeof DashboardCoursesNewRoute
}

const DashboardCoursesRouteChildren: DashboardCoursesRouteChildren = {
  DashboardCoursesCourseIdRoute: DashboardCoursesCourseIdRoute,
  DashboardCoursesNewRoute: DashboardCoursesNewRoute,
}

const DashboardCoursesRouteWithChildren =
  DashboardCoursesRoute._addFileChildren(DashboardCoursesRouteChildren)

interface DashboardDiscussionsRouteChildren {
  DashboardDiscussionsDiscussionIdRoute: typeof DashboardDiscussionsDiscussionIdRoute
}

const DashboardDiscussionsRouteChildren: DashboardDiscussionsRouteChildren = {
  DashboardDiscussionsDiscussionIdRoute: DashboardDiscussionsDiscussionIdRoute,
}

const DashboardDiscussionsRouteWithChildren =
  DashboardDiscussionsRoute._addFileChildren(DashboardDiscussionsRouteChildren)

interface DashboardQuizzesRouteChildren {
  DashboardQuizzesQuizIdRoute: typeof DashboardQuizzesQuizIdRoute
}

const DashboardQuizzesRouteChildren: DashboardQuizzesRouteChildren = {
  DashboardQuizzesQuizIdRoute: DashboardQuizzesQuizIdRoute,
}

const DashboardQuizzesRouteWithChildren =
  DashboardQuizzesRoute._addFileChildren(DashboardQuizzesRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRouteWithChildren
  DashboardCatalogRoute: typeof DashboardCatalogRoute
  DashboardCategoriesRoute: typeof DashboardCategoriesRoute
  DashboardCertificatesRoute: typeof DashboardCertificatesRouteWithChildren
  DashboardContinueRoute: typeof DashboardContinueRoute
  DashboardCoursesRoute: typeof DashboardCoursesRouteWithChildren
  DashboardDiscussionsRoute: typeof DashboardDiscussionsRouteWithChildren
  DashboardEnrollmentsRoute: typeof DashboardEnrollmentsRoute
  DashboardInstructorsRoute: typeof DashboardInstructorsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardQuizzesRoute: typeof DashboardQuizzesRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStudentsRoute: typeof DashboardStudentsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardAssignmentsRoute: DashboardAssignmentsRouteWithChildren,
  DashboardCatalogRoute: DashboardCatalogRoute,
  DashboardCategoriesRoute: DashboardCategoriesRoute,
  DashboardCertificatesRoute: DashboardCertificatesRouteWithChildren,
  DashboardContinueRoute: DashboardContinueRoute,
  DashboardCoursesRoute: DashboardCoursesRouteWithChildren,
  DashboardDiscussionsRoute: DashboardDiscussionsRouteWithChildren,
  DashboardEnrollmentsRoute: DashboardEnrollmentsRoute,
  DashboardInstructorsRoute: DashboardInstructorsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardQuizzesRoute: DashboardQuizzesRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStudentsRoute: DashboardStudentsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VerifyCertificateIdRoute: VerifyCertificateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
